# Generated by Django 4.0.5 on 2022-09-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='signature',
            field=models.FileField(default=None, null=True, upload_to='uploads/'),
        ),
    ]
