# Generated by Django 4.0.5 on 2022-09-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_personalinfo_altphone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='altphone',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='cnfpassword',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='reference',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='resume',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='signature',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='uploadpicture',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/'),
        ),
    ]
