# Generated by Django 4.0.5 on 2022-09-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_workexp_user_alter_personalinfo_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexp',
            name='designation',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
