# Generated by Django 4.1.4 on 2022-12-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_personalinfo_companylogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='companylogo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='signature',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='workexp',
            name='designation',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
