# Generated by Django 4.1.7 on 2023-07-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_patientinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
            ],
        ),
    ]
