# Generated by Django 4.1.7 on 2023-07-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_serviceslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='services',
            field=models.ManyToManyField(to='users.serviceslist'),
        ),
    ]
