# Generated by Django 4.1.7 on 2023-08-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_services_personalinfo_serviceslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='blood',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='height',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='pulse',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='weight',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
