# Generated by Django 4.1.7 on 2023-09-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_patientinfo_blood_patientinfo_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='ColorBlindness',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='FarVisionLeft',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='FarVisionRight',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='NearVisionLeft',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='NearVisionRight',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
