# Generated by Django 4.1.7 on 2023-09-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_patientinfo_colorblindness_patientinfo_farvisionleft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='PatientId',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='PatientName',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='ReportDate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='TestDate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='age',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='gender',
            field=models.CharField(max_length=50),
        ),
    ]
