# Generated by Django 4.1.7 on 2023-10-03 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_patientinfo_patientid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_field', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientId', models.CharField(max_length=15)),
                ('PatientName', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=15)),
                ('HeartRate', models.CharField(blank=True, max_length=30, null=True)),
                ('TestDate', models.CharField(max_length=20)),
                ('ReportDate', models.CharField(max_length=20)),
                ('reportimage', models.URLField(blank=True, null=True)),
                ('cardiologist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.personalinfo')),
                ('date', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.date')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('technician_name', models.CharField(default='Unknown Technician', max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.city')),
            ],
        ),
        migrations.AddField(
            model_name='date',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.location'),
        ),
        migrations.AddField(
            model_name='city',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client'),
        ),
    ]
