# Generated by Django 4.0.5 on 2023-11-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_city_client_date_patientdetails_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='audioPatientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientId', models.CharField(max_length=15)),
                ('PatientName', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=15)),
                ('TestDate', models.CharField(max_length=20)),
                ('ReportDate', models.CharField(max_length=20)),
                ('rightEarDB', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('leftEarDB', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('rightEarBoneDB', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('leftEarBoneDB', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
    ]
