# Generated by Django 4.2.7 on 2023-11-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_audiopatientdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiopatientdetails',
            name='leftEarLevel',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='audiopatientdetails',
            name='rightEarLevel',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
