# Generated by Django 4.2.7 on 2023-11-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_optopatientdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='vitalPatientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientId', models.CharField(max_length=50)),
                ('PatientName', models.CharField(max_length=70)),
                ('age', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('TestDate', models.CharField(max_length=50)),
                ('ReportDate', models.CharField(max_length=50)),
                ('height', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('weight', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('blood', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('pulse', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
    ]
