# Generated by Django 4.2.7 on 2023-12-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_optopatientdetails_vitalpatientdetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DICOMData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(blank=True, max_length=50)),
                ('patient_id', models.CharField(blank=True, max_length=20)),
                ('age', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('study_date', models.CharField(blank=True, max_length=50)),
                ('study_description', models.CharField(blank=True, max_length=100)),
                ('dicom_file', models.FileField(upload_to='uploads/')),
                ('jpeg_file', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
