# Generated by Django 3.1.3 on 2023-12-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20231206_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='PRInterval',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
