# Generated by Django 3.1.3 on 2023-12-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_patientdetails_printerval'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomdata',
            name='isDone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='isDone',
            field=models.BooleanField(default=False),
        ),
    ]
