# Generated by Django 3.1.3 on 2023-12-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20231216_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomdata',
            name='notes',
            field=models.CharField(default=True, max_length=50000),
        ),
    ]
