# Generated by Django 3.1.3 on 2023-12-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_dicomdata_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='PatientId',
            field=models.CharField(max_length=50),
        ),
    ]
