# Generated by Django 3.1.3 on 2024-01-04 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_coordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomdata',
            name='radiologist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.personalinfo'),
        ),
    ]
